### ISSUE TITLE
When minifying json with strings containing brackets, spaces are trimmed

### ISSUE THREAD

**Issue by joanjane** [neilcarpenter/gulp-pretty-data#7]
Hi there!
I've played around with prettyData on json files and seems to have an issue when a string of json contains brackets like this:
```json
{
  "welcome": "text before {{variable}} text after"
}
```
To
```json
{"welcome":"text before{{variable}}text after"}
```
*note spaces missing between {{variable}}

**Comment by neilcarpenter** [comment]
Hey! This plugin is just a wrapper around a node [pretty-data plugin](https://github.com/vkiryukhin/pretty-data) so if there's any bugs with minification it would really need to be fixed there...

**Comment by joanjane** [comment]
You are right, this issue should be closed then. I've created the issue on pretty-data.
